import Header from "./components/header";
import Navbar from "./components/navbar";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./components/footer";
import { ClerkProvider } from '@clerk/nextjs';
import ReduxProvider from "./components/reduxprovider";
import { Suspense } from "react";

// Ensure the async behavior of ClerkProvider is handled inside Suspense
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // Wrap ClerkProvider inside Suspense to handle async loading
    <Suspense fallback={<div>Loading...</div>}>
      <ClerkProvider>
        <ReduxProvider>
          <html lang="en">
            <body>
              <Header />
              <Navbar />
              {children}
              <Footer />
            </body>
          </html>
        </ReduxProvider>
      </ClerkProvider>
    </Suspense>
  );
}
