import Header from "./components/header";
import Navbar from "./components/navbar";
import Footer from "./components/footer";
import ReduxProvider from "./components/reduxprovider";
import { ClerkProvider } from '@clerk/nextjs';
import { Inter } from "next/font/google";
import { Metadata } from "next";  // Import Metadata here for server-side use

const inter = Inter({ subsets: ["latin"] });

// Server-side metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <ReduxProvider>
        <html lang="en">
          <body className={inter.className}>
            <Header />
            <Navbar />
            {children}
            <Footer />
          </body>
        </html>
      </ReduxProvider>
    </ClerkProvider>
  );
}
