import Header from "./components/header"
import Navbar from "./components/navbar"
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./components/footer";

import './globals.css';
import ReduxProvider from "./components/reduxprovider";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Suspense fallback={<div>Loading...</div>}>
    
        <ReduxProvider>
          <html lang="en">
            <body>
              <Header />
              <Navbar />
              {children}
              <Footer />
            </body>
          </html>
        </ReduxProvider>
      
    </Suspense>
  );
}
